language: generic

os:
  - linux

dist:
  - trusty
  - xenial

env:
  global:
    - secure: "CoI8hwHH1yfQoQxIfWGRS0WfTyScox+5aJn0fDDgz2uKrrIxmBvIw/WKX8wcSiV6fLmLuwgNkKqSM3hdO4qaG+JxfWcuEiZZHm+kxSGMkWbGb/fvAI+gHg8ldKyYttcIX71O5rlZiC2QpNKQi2v18S6pI5p8eqnx7DYx4YrmguQ="
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
    - secure: "C9ZJ9LYnuowRdF4D66KLfquimvu8GtRGIafwvCcGYKReEy8phlBdFsHlybkMBNYJNTJSM0j6wyo1lKTVGHxmpQDimjR7kmxUtawbhuJ5qOCBtFqNVh9lRQi7hC4+UOhvRsIcbV8HAJM5u/5RxGOfXCePK3a2DtiYv1d2NHToZN8="

notifications:
  webhooks: https://coveralls.io/webhook

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - libcap2-bin
      - libtest-command-perl
    
script:
  - ci/build-4-compile.sh
  - ci/run-tests.sh
  - ci/deploy-coveralls.sh

stages:
  - test
  - name: deploy
    if: branch = master OR branch = v4.x
  - name: coverity
    if: branch = master OR branch = v4.x OR branch = coverity_scan

jobs:
  include:
    #### STAGE: test
    - stage: test
      name: test trusty
      os: linux
      dist: trusty
      env:
        - SKIP_IPV6=1
      install:
        - ci/build-1-autotools.sh

    - name: test xenial
      os: linux
      dist: xenial
      env:
        - SKIP_IPV6=1

    - name: test bionic
      os: linux
      dist: bionic
      env:
        - SKIP_IPV6=1

    - name: test bionic lxd arm64
      os: linux
      dist: bionic
      arch: arm64

    - name: test macos
      os: osx
      install:
        - ci/build-2-test-command.sh
        - ci/build-3-prepare-macos.sh
      env:
        - SKIP_IPV6=1

    #### STAGE: deploy
    - stage: deploy
      name: deploy
      os: linux
      dist: xenial
      after_success:
        - ci/deploy-bintray.sh

    #### STAGE: coverity
    - stage: coverity
      name: coverity
      os: linux
      dist: xenial
      script:
        - ci/deploy-coverity.sh
